FROM golang:1.13 AS build-env

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0

RUN apt-get update && apt-get install libsystemd-dev -y

RUN mkdir -p /workspace
WORKDIR /workspace

ADD go.mod go.sum ./
RUN go mod download

# ADD . .
